# Generated by Django 4.0.4 on 2022-04-25 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='access_token',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='date_auth',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='refresh_token',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='scope',
            field=models.CharField(default=None, max_length=191),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='spotify_display_name',
            field=models.CharField(default=None, max_length=191),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='spotify_user_id',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
