# Generated by Django 4.0.4 on 2022-04-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_alter_spotifyuser_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='access_token',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='refresh_token',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='scope',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='spotify_display_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='spotify_user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
