# Generated by Django 4.0.4 on 2022-04-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_alter_spotifyuser_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='spotify_user_id',
            field=models.CharField(max_length=50),
        ),
    ]
