# Generated by Django 4.0.4 on 2022-04-27 00:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_alter_spotifyuser_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='date_auth',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
