# Generated by Django 4.0.4 on 2022-04-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_alter_spotifyuser_date_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmplaylist',
            name='bpm_end',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='bpmplaylist',
            name='bpm_start',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
