# Generated by Django 4.0.4 on 2022-04-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_alter_bpmplaylist_bpm_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpmplaylist',
            name='public',
        ),
    ]
