# Generated by Django 4.0.4 on 2022-04-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_remove_bpmplaylist_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmplaylist',
            name='name',
            field=models.CharField(default='tbd', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bpmplaylist',
            name='playlist_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
