# Generated by Django 4.0.4 on 2022-05-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0009_bpmplaylist_name_alter_bpmplaylist_playlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmplaylist',
            name='bpm_end',
            field=models.PositiveSmallIntegerField(help_text='Please enter a positive integer. It must be greater or equal to the starting bpm.', verbose_name='Ending bpm'),
        ),
        migrations.AlterField(
            model_name='bpmplaylist',
            name='bpm_start',
            field=models.PositiveSmallIntegerField(help_text='Please enter a positive integer. It must be smaller or equal to the ending bpm.', verbose_name='Starting bpm'),
        ),
        migrations.AlterField(
            model_name='bpmplaylist',
            name='multiples_bpm',
            field=models.BooleanField(default=True, help_text='If you select this, tracks with bpms that are multiples of the ones in the selected bpm range will also be added to the playlist. This means faster songs may be added, but slower songs will not be added.', verbose_name='Include multiples'),
        ),
        migrations.AlterField(
            model_name='bpmplaylist',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Playlist name'),
        ),
    ]
